services:
  node-server:
    restart: always
    build: 
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    networks:
      - my-network
    command: sh setup.sh

networks:
  my-network:
